// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package socket

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadTcp2udp returns the embedded CollectionSpec for tcp2udp.
func loadTcp2udp() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Tcp2udpBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcp2udp: %w", err)
	}

	return spec, err
}

// loadTcp2udpObjects loads tcp2udp and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcp2udpObjects
//	*tcp2udpPrograms
//	*tcp2udpMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcp2udpObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcp2udp()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcp2udpSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcp2udpSpecs struct {
	tcp2udpProgramSpecs
	tcp2udpMapSpecs
	tcp2udpVariableSpecs
}

// tcp2udpProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcp2udpProgramSpecs struct {
	TcTcpToPaqet *ebpf.ProgramSpec `ebpf:"tc_tcp_to_paqet"`
}

// tcp2udpMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcp2udpMapSpecs struct {
	TargetPort *ebpf.MapSpec `ebpf:"target_port"`
}

// tcp2udpVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcp2udpVariableSpecs struct {
}

// tcp2udpObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcp2udpObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcp2udpObjects struct {
	tcp2udpPrograms
	tcp2udpMaps
	tcp2udpVariables
}

func (o *tcp2udpObjects) Close() error {
	return _Tcp2udpClose(
		&o.tcp2udpPrograms,
		&o.tcp2udpMaps,
	)
}

// tcp2udpMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcp2udpObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcp2udpMaps struct {
	TargetPort *ebpf.Map `ebpf:"target_port"`
}

func (m *tcp2udpMaps) Close() error {
	return _Tcp2udpClose(
		m.TargetPort,
	)
}

// tcp2udpVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcp2udpObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcp2udpVariables struct {
}

// tcp2udpPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcp2udpObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcp2udpPrograms struct {
	TcTcpToPaqet *ebpf.Program `ebpf:"tc_tcp_to_paqet"`
}

func (p *tcp2udpPrograms) Close() error {
	return _Tcp2udpClose(
		p.TcTcpToPaqet,
	)
}

func _Tcp2udpClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcp2udp_bpfel.o
var _Tcp2udpBytes []byte
